[33mcommit 847eb9811e064ce39380a80ac711d154904e33b9[m[33m ([m[1;31mupstream/newDevelop[m[33m, [m[1;31morigin/newDevelop[m[33m, [m[1;31morigin/KevinBetaTesting[m[33m, [m[1;32mnewDevelop[m[33m)[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Wed Aug 22 10:14:16 2018 +0800

    ok

[33mcommit 677337dcef1a0752c8c51fa98096cdb2add13e4c[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Wed Aug 22 09:37:03 2018 +0800

    signup signin

[33mcommit 15bbfca7b9534f78ba3853306942d3f1c1a23ae4[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Mon Aug 20 23:37:24 2018 +0800

    fixed signup & signin,still need 2 code back btn

[33mcommit 19676d9afc9adb4e81c4c387e1304033fe90fc73[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Mon Aug 20 23:15:28 2018 +0800

    edited some codes

[33mcommit 763ab64e81cac73368dbe0c8cca2d7b876bc8e04[m
Merge: 7ab32e1 405d716
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Mon Aug 20 22:55:48 2018 +0800

    Merge branch 'ray' of https://github.com/SpectreSpammer/Mobile-Inventory-App into KevinBetaTesting

[33mcommit 7ab32e10946b9e4124d2dcf94551bf960cfd5725[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Mon Aug 20 22:20:42 2018 +0800

    fetch head

[33mcommit 405d716a59fe3b6bcda7b1aef2879f807c9e5784[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Mon Aug 20 15:24:16 2018 +0800

    Finish whole codes and Beta Testing now

[33mcommit 9beb9051cb6b24ad10d1ca25d755e8f586115460[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Fri Aug 17 20:02:18 2018 +0800

    deleting kevins work

[33mcommit 0537b6bfcb06e4c4215dba34684964f0a959be5d[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Fri Aug 17 19:55:31 2018 +0800

    Database creation

[33mcommit 1beadeaa399de11367386c842e6547fecf6eaaac[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Fri Aug 17 11:15:05 2018 +0800

    Adding codes for SigninActivity ,SignupActivity

[33mcommit 2189d6e7cdff28c242d2a1ad97bc7ab83f243733[m
Merge: a4cec17 39d0c51
Author: raynand <raynandnavarra07@gmail.com>
Date:   Thu Aug 16 18:21:56 2018 +0800

    Merge branch 'ray' into develop

[33mcommit a4cec17619a1bca753cbf4ec1922d74e517eb297[m[33m ([m[1;31mupstream/master[m[33m, [m[1;31morigin/master[m[33m, [m[1;32mmaster[m[33m)[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Thu Aug 16 17:35:21 2018 +0800

    Intent in Signin and Signup

[33mcommit 66d65b3add7224ddea0bf1aff2f25fbc9c9a97fd[m
Merge: 6c91611 6dce15e
Author: raynand <raynandnavarra07@gmail.com>
Date:   Thu Aug 16 17:32:32 2018 +0800

    Merge branch 'master' of https://github.com/SpectreSpammer/Mobile-Inventory-App into develop

[33mcommit 39d0c51bf78ce49c00803d020e76848695ef9017[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Thu Aug 16 17:27:44 2018 +0800

    Intent button for Signin and Signup

[33mcommit 6c91611c52b3c3c18ebea63f7bdf52984f712ec4[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Thu Aug 16 17:24:28 2018 +0800

    Intent in Homepage by Raynand

[33mcommit 6dce15e984cdcf73c18d550746587255bf0d5e98[m[33m ([m[1;31morigin/kevinInventoryDb[m[33m)[m
Merge: 34a177c e3c148b
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Thu Aug 16 13:20:53 2018 +0800

    Merge branch 'develop'

[33mcommit e3c148bc96e012a6c3401cd5e9215858486a6bb0[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Thu Aug 16 13:14:57 2018 +0800

    added some code for additemactivity and inventoryactivity

[33mcommit dda580eaed2ee8086bdefffbcee0e8abad874753[m[33m ([m[1;31morigin/kevinViewItem[m[33m)[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Thu Aug 16 11:21:45 2018 +0800

    Kevin View Item edit 1

[33mcommit f04a75277f95f990b4e7c92eb405ed665411404e[m[33m ([m[1;31morigin/kevinAddItem[m[33m)[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Thu Aug 16 10:51:05 2018 +0800

    Kevin Add Item edit 2

[33mcommit 6080d5bc41c32b56fb2073ebd963568b2e4b755e[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Thu Aug 16 10:24:01 2018 +0800

    AddItemActivity Commit

[33mcommit 7a1e4207510154a97328ffc4ac55a7e3dba0ddf3[m[33m ([m[1;31morigin/kevinInventory[m[33m)[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Wed Aug 15 18:08:39 2018 +0800

    added list view and button

[33mcommit 34a177c69e4b481d49d1ba336a465278710003ad[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Wed Aug 15 17:29:00 2018 +0800

    Initial commit

[33mcommit 9c74dc334c24e976d76fce4184fb1ff0bfafe0b9[m
Merge: 01ecaa9 53f8422
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Wed Aug 15 12:31:04 2018 +0800

    Merge branch 'kevin' into develop

[33mcommit 53f8422eaa399242eec1c61237e16b671b8304b7[m[33m ([m[1;31morigin/kevin[m[33m)[m
Author: Kevin Baguisa <kevinbaguisa@outlook.com>
Date:   Wed Aug 15 12:27:50 2018 +0800

    Initial commit

[33mcommit 01ecaa9811c5b19183eed54175f9f842fb0513ef[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Wed Aug 15 11:30:33 2018 +0800

    Home , Signin and Signup

[33mcommit 7eb15786525e3a084d067ac8de0efcbf94935f99[m[33m ([m[1;32mkevin[m[33m)[m
Author: raynand <raynandnavarra07@gmail.com>
Date:   Wed Aug 15 11:23:54 2018 +0800

    Hi
